SET_FLOATING_FEATURE_CONFIG "SEC_FLOATING_FEATURE_FRAMEWORK_SUPPORT_BLOCKCHAIN_SERVICE" --delete

if [ "$TARGET_SINGLE_SYSTEM_IMAGE" == "qssi" ]; then
    :
elif [ "$TARGET_SINGLE_SYSTEM_IMAGE" == "essi" ]; then
    ADD_TO_WORK_DIR "gts9fexx" "system" "system/bin" 0 2000 751 "u:object_r:system_file:s0"
    ADD_TO_WORK_DIR "gts9fexx" "system" "system/lib/libandroid_servers.so" 0 0 644 "u:object_r:system_lib_file:s0"More actions
    ADD_TO_WORK_DIR "gts9fexx" "system" "system/lib/libmdf.so" 0 0 644 "u:object_r:system_lib_file:s0"
    ADD_TO_WORK_DIR "gts9fexx" "system" "system/lib64/libandroid_servers.so" 0 0 644 "u:object_r:system_lib_file:s0"
    ADD_TO_WORK_DIR "gts9fexx" "system" "system/lib64/libepm.so" 0 0 644 "u:object_r:system_lib_file:s0"
    ADD_TO_WORK_DIR "gts9fexx" "system" "system/lib64/libmdf.so" 0 0 644 "u:object_r:system_lib_file:s0"
elif [ "$TARGET_SINGLE_SYSTEM_IMAGE" == "self" ]; then
    return 0
fi

DELETE_FROM_WORK_DIR "system" "system/app/BlockchainBasicKit"
DELETE_FROM_WORK_DIR "system" "system/bin/dualdard"
DELETE_FROM_WORK_DIR "system" "system/bin/sem_daemon"
DELETE_FROM_WORK_DIR "system" "system/etc/init/dualdard.rc"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/com.samsung.android.nfc.mpos.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.knox.vpn.proxyhandler.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.hdmapp.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.kgclient.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.analytics.uploader.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.app.networkfilter.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.er.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.kfbp.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.knnr.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.kpecore.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.mpos.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.pushmanager.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.sandbox.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.knox.zt.framework.xml"
DELETE_FROM_WORK_DIR "system" "system/etc/public.libraries-wsm.samsung.txt"
DELETE_FROM_WORK_DIR "system" "system/etc/sysconfig/preinstalled-packages-com.samsung.android.coldwalletservice.xml"
DELETE_FROM_WORK_DIR "system" "system/framework/com.samsung.android.nfc.mpos.jar"
DELETE_FROM_WORK_DIR "system" "system/framework/service-samsung-blockchain.jar"
DELETE_FROM_WORK_DIR "system" "system/lib/android.hardware.weaver@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib/hidl_comm_ddar_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib/hidl_tlc_blockchain_comm_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib/hidl_tlc_payment_comm_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libdualdar.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libepm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libhal.wsm.samsung.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libhermes_cred.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libhidl_comm_mpos_tui_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libkeyutils.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libknox_filemanager.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libpersona.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libsec_sem.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libsec_semRil.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libsec_semTlc.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libspictrl.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_blockchain_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_blockchain_direct_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_blockchain_keystore.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_payment_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_payment_direct_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib/libtlc_payment_spay.so"
DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.mpos-V1-ndk.so"
DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.security.wsm.service-V1-ndk.so"
DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.tlc.blockchain@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.tlc.ddar@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.tlc.mpos_tui@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.tlc.payment@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/hidl_comm_ddar_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/hidl_tlc_blockchain_comm_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/hidl_tlc_payment_comm_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libdualdar.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libhal.wsm.samsung.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libhermes_cred.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libhidl_comm_mpos_tui_client.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libsec_sem.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libsec_semRil.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libsec_semTlc.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libspictrl.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_blockchain_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_blockchain_direct_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_blockchain_keystore.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_payment_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_payment_direct_comm.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/libtlc_payment_spay.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.mpos-V1-ndk.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.security.wsm.service-V1-ndk.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.tlc.blockchain@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.tlc.ddar@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.tlc.mpos_tui@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.tlc.payment@1.0.so"
DELETE_FROM_WORK_DIR "system" "system/priv-app/HdmApk"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KPECore"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxCore"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxERAgent"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxFrameBufferProvider"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxGuard"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxMposAgent"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxNetworkFilter"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxNeuralNetworkRuntime"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxPushManager"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxSandbox"
DELETE_FROM_WORK_DIR "system" "system/priv-app/KnoxZtFramework"
DELETE_FROM_WORK_DIR "system" "system/priv-app/SEMFactoryApp"
DELETE_FROM_WORK_DIR "system" "system/priv-app/knoxanalyticsagent"
DELETE_FROM_WORK_DIR "system" "system/priv-app/knoxvpnproxyhandler"
if [[ "$TARGET_API_LEVEL" -ge 34 ]]; then
    DELETE_FROM_WORK_DIR "system" "system/bin/fabric_crypto"
    DELETE_FROM_WORK_DIR "system" "system/etc/vintf/manifest/fabric_crypto_manifest.xml"
    DELETE_FROM_WORK_DIR "system" "system/etc/permissions/FabricCryptoLib.xml"
    DELETE_FROM_WORK_DIR "system" "system/etc/init/fabric_crypto.rc"
    DELETE_FROM_WORK_DIR "system" "system/etc/permissions/privapp-permissions-com.samsung.android.kmxservice.xml"
    DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.security.fkeymaster-V1-cpp.so"
    DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.security.fkeymaster-V1-ndk.so"
    DELETE_FROM_WORK_DIR "system" "system/lib64/com.samsung.security.fabric.cryptod-V1-cpp.so"
    DELETE_FROM_WORK_DIR "system" "system/framework/FabricCryptoLib.jar"
    DELETE_FROM_WORK_DIR "system" "system/priv-app/KmxService"
fi

if [[ "$TARGET_SINGLE_SYSTEM_IMAGE" = "qssi" ]]; then
    DELETE_FROM_WORK_DIR "system" "system/lib/libsec_semAidl.so"
    DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.security.sem-V1-ndk.so"
    DELETE_FROM_WORK_DIR "system" "system/lib64/libsec_semAidl.so"
    DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.security.sem-V1-ndk.so"
fi

if [[ "$TARGET_SINGLE_SYSTEM_IMAGE" = "essi" ]]; then
    DELETE_FROM_WORK_DIR "system" "system/lib/libsec_semHal.so"
    DELETE_FROM_WORK_DIR "system" "system/lib/vendor.samsung.hardware.security.sem@1.0.so"
    DELETE_FROM_WORK_DIR "system" "system/lib64/libsec_semHal.so"
    DELETE_FROM_WORK_DIR "system" "system/lib64/vendor.samsung.hardware.security.sem@1.0.so"
fi
